version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: db
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
  backend:
    container_name: backend
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static
      - media:/media
  frontend:
    container_name: frontend
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    container_name: gateway
    build: ./nginx/
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend